CREATE TABLE IF NOT EXISTS T_BOOK_INFO (
  ID            INTEGER PRIMARY KEY AUTO_INCREMENT,
  NAME          varchar(255) NOT NULL,
  UPDATED_TIME	TIMESTAMP
);

INSERT INTO T_BOOK_INFO(NAME, UPDATED_TIME) VALUES('BOOK_1', CURRENT_TIMESTAMP);
INSERT INTO T_BOOK_INFO(NAME, UPDATED_TIME) VALUES('BOOK_2', CURRENT_TIMESTAMP);
INSERT INTO T_BOOK_INFO(NAME, UPDATED_TIME) VALUES('BOOK_3', CURRENT_TIMESTAMP);